title: Dan Johnson
email:
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer with an eye for design - specialising in React and PHP.
github_username: danjohnson95
minimal_mistakes_skin: contrast
remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dan Johnson"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software engineer with an 👁 for design - specialising in React and PHP."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/danjohnson95"
